/** Declaration file generated by dts-gen */


class Stats {
    showPanel(n);
    addPanel(panel);
    dom;
    begin();
    end();
}

declare namespace Stats {

    class Panel {
        constructor(name, fg, bg);
    }
}

declare module "Stats" {
    export = Stats;
}
